# RustSmartScope 配置文件

[app]
name = "RustSmartScope"
version = "1.0.0"
log_level = "info"
log_file = "logs/rustsmartscope.log"

# 相机配置
[camera]
width = 1280
height = 720
fps = 30

[camera.left]
name = ["cameraL", "cameral", "left", "video3", "1.3"]
parameters_path = "camera_parameters/camera0_intrinsics.dat"
rot_trans_path = "camera_parameters/camera0_rot_trans.dat"

[camera.right]
name = ["cameraR", "camerar", "right", "video1", "1.3.3"]
parameters_path = "camera_parameters/camera1_intrinsics.dat"
rot_trans_path = "camera_parameters/camera1_rot_trans.dat"

# 相机参数调节配置
[camera.control]
auto_exposure = true
exposure_time = 10000     # 微秒
gain = 1.0
auto_white_balance = true
brightness = 0
contrast = 0
saturation = 0

# 立体匹配配置
[stereo]
matcher = "sgbm"          # 可选: "bm", "sgbm", "neural"
min_disparity = 0
num_disparities = 128
block_size = 9
p1 = 200
p2 = 800
disp12_max_diff = 1
pre_filter_cap = 31
uniqueness_ratio = 15
speckle_window_size = 100
speckle_range = 32

# UI配置
[ui]
language = "zh_CN"
theme = "dark"
show_fps = true
window_width = 1920
window_height = 1080

# 日志配置
[logging]
level = "info"                     # 可选: "debug", "info", "warning", "error"
file_path = "logs/rustsmartscope.log"
max_file_size = 10485760           # 10MB
backup_count = 5