# SmartScope 配置文件（精简版）
## 说明：当前版本仅使用相机基础参数，其他信息由系统自动检测或在运行时控制

[camera]
width = 1280
height = 720
fps = 30

[camera.left]
name_keywords = ["cameral", "left", "video3"]

[camera.right]
name_keywords = ["camerar", "right", "video1"]
