[camera]
width = 1280
height = 720
fps = 30

[camera.left]
name_keywords = [
    "cameral",
    "left",
]
parameters_path = "camera_parameters/camera0_intrinsics.dat"
rot_trans_path = "camera_parameters/camera0_rot_trans.dat"

[camera.right]
name_keywords = [
    "camerar",
    "right",
]
parameters_path = "camera_parameters/camera1_intrinsics.dat"
rot_trans_path = "camera_parameters/camera1_rot_trans.dat"

[camera.control]
auto_exposure = true
exposure_time = 10000
gain = 1.0
auto_white_balance = true
brightness = 0
contrast = 0
saturation = 0

[storage]
location = "external"
external_device = "/dev/mmcblk1p1"
internal_base_path = "/home/eddysun/data"
external_relative_path = "EAI-520_data"
auto_recover = false
