# SmartScope 配置文件
# 完整的立体视觉系统配置

[app]
name = "RustSmartScope"
version = "0.1.0"
window_width = 1920
window_height = 1080

[camera]
width = 1280
height = 720
fps = 30

[camera.left]
name_keywords = ["cameral", "left", "video3"]
parameters_path = "camera_parameters/camera0_intrinsics.dat"
rot_trans_path = "camera_parameters/camera0_rot_trans.dat"

[camera.right]
name_keywords = ["camerar", "right", "video1"]
parameters_path = "camera_parameters/camera1_intrinsics.dat"
rot_trans_path = "camera_parameters/camera1_rot_trans.dat"

[camera.control]
auto_exposure = true
exposure_time = 10000
gain = 1.0
auto_white_balance = true
brightness = 0
contrast = 0
saturation = 0

[stereo]
matcher = "sgbm"
min_disparity = 0
num_disparities = 128
block_size = 9
p1 = 200
p2 = 800
disp12_max_diff = 1
pre_filter_cap = 31
uniqueness_ratio = 15
speckle_window_size = 100
speckle_range = 32

[stereo.neural]
model_path = "models/stereo_model.onnx"
provider = "cuda"

[stereo.point_cloud]
max_points = 1000000
filter_outliers = true
voxel_size = 0.01

[hardware.hid]
vendor_id = 0x0001
product_id = 0xEDD1
usage_page = 0xFF60
usage = 0x61
report_size = 33
timeout_ms = 1000

[hardware.device]
light_level = 2
lens_locked = false
lens_speed = 50
servo_x_angle = 90.0
servo_y_angle = 90.0

[hardware.processing]
rotation_enabled = false
rotation_angle = 0.0
correction_enabled = true
stereo_rectification_enabled = true
disparity_enabled = true
disparity_quality = "Medium"

[ui]
language = "zh_CN"
theme = "dark"
show_fps = true
auto_save = true

[measurement]
unit = "mm"
precision = 2
save_path = "measurements/"
max_reasonable_depth_mm = 10000.0
max_reasonable_length_mm = 10000.0
max_reasonable_area_mm2 = 1000000.0

[logging]
level = "info"
file_path = "logs/smartscope.log"
max_file_size = 10485760  # 10MB
backup_count = 5
enable_detailed_logging = true

[performance]
enable_parallel_processing = true
max_threads = 4
enable_gpu_acceleration = true